language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t penquinspecz/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true penquinspecz/docker-react npm run test